formulario2/Models/ErrorViewModel.cs
namespace formulario2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

formulario2/Models/membro.cs
using System.ComponentModel.DataAnnotations;

namespace formulario2.Models
{
    public class membro
    {
        [Key]
        public int Codigo { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string UltimoNome { get; set; }
        [Required]
        public string Endereco { get; set; }
        [Required]
        public string Endereco2 { get; set; }
        [Required]
        public string Cidade { get; set; }
        [Required]
        public string Est { get; set; }
        [Required]
        public int Postal { get; set; }
    }
}

formulario2/Controllers/HomeController.cs
using formulario2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace formulario2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

formulario2/Controllers/membroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using formulario2.Data;
using formulario2.Models;

namespace formulario2.Controllers
{
    public class membroController : Controller
    {
        private readonly formulario2Context _context;

        public membroController(formulario2Context context)
        {
            _context = context;
        }

        // GET: membro
        public async Task<IActionResult> Index()
        {
            return View(await _context.membro.ToListAsync());
        }

        // GET: membro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membro = await _context.membro
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (membro == null)
            {
                return NotFound();
            }

            return View(membro);
        }

        // GET: membro/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: membro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Nome,UltimoNome,Endereco,Endereco2,Cidade,Est,Postal")] membro membro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(membro);
        }

        // GET: membro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membro = await _context.membro.FindAsync(id);
            if (membro == null)
            {
                return NotFound();
            }
            return View(membro);
        }

        // POST: membro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Codigo,Nome,UltimoNome,Endereco,Endereco2,Cidade,Est,Postal")] membro membro)
        {
            if (id != membro.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!membroExists(membro.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(membro);
        }

        // GET: membro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membro = await _context.membro
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (membro == null)
            {
                return NotFound();
            }

            return View(membro);
        }

        // POST: membro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membro = await _context.membro.FindAsync(id);
            if (membro != null)
            {
                _context.membro.Remove(membro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool membroExists(int id)
        {
            return _context.membro.Any(e => e.Codigo == id);
        }
    }
}

formulario2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de formulário</p>
</div>

formulario2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - formulario2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/formulario2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">formulario2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="membro" asp-action="Index">Formulario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - formulario2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

formulario2/Views/membro/Create.cshtml
@model formulario2.Models.membro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>membro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimoNome" class="control-label"></label>
                <input asp-for="UltimoNome" class="form-control" />
                <span asp-validation-for="UltimoNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco2" class="control-label"></label>
                <input asp-for="Endereco2" class="form-control" />
                <span asp-validation-for="Endereco2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Est" class="control-label"></label>
                <input asp-for="Est" class="form-control" />
                <span asp-validation-for="Est" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postal" class="control-label"></label>
                <input asp-for="Postal" class="form-control" />
                <span asp-validation-for="Postal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

formulario2/Views/membro/Delete.cshtml
@model formulario2.Models.membro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>membro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UltimoNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UltimoNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Est)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Est)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Codigo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

formulario2/Views/membro/Details.cshtml
@model formulario2.Models.membro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>membro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UltimoNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UltimoNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Est)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Est)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Codigo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

formulario2/Views/membro/Edit.cshtml
@model formulario2.Models.membro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>membro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Codigo" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimoNome" class="control-label"></label>
                <input asp-for="UltimoNome" class="form-control" />
                <span asp-validation-for="UltimoNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco2" class="control-label"></label>
                <input asp-for="Endereco2" class="form-control" />
                <span asp-validation-for="Endereco2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Est" class="control-label"></label>
                <input asp-for="Est" class="form-control" />
                <span asp-validation-for="Est" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postal" class="control-label"></label>
                <input asp-for="Postal" class="form-control" />
                <span asp-validation-for="Postal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

formulario2/Views/membro/Index.cshtml
@model IEnumerable<formulario2.Models.membro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimoNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Est)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UltimoNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Est)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postal)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Codigo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Codigo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Codigo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>